apiVersion: apps/v1
kind: Deployment
metadata:
  name: cli
spec:
  selector:
    matchLabels:
      app: cli
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: cli
    spec:
      nodeName: test-instance
      containers:
      - image: hyperledger/fabric-tools:1.4.0
        name: cli
        imagePullPolicy: Never
        workingDir: /opt/gopath/src/github.com/hyperledger/fabric/peer
        command: ["/bin/bash"]
        tty: true
        stdin: true
        env:
        - name: CORE_PEER_ADDRESS
          value: peer0:7051
        - name: CORE_PEER_ID
          value: cli
        - name: CORE_PEER_LOCALMSPID
          value: Org1MSP
        - name: CORE_PEER_MSPCONFIGPATH
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/users/Admin@org1.example.com/msp
        - name: CORE_PEER_TLS_CERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.crt
        - name: CORE_PEER_TLS_ENABLED
          value: "true"
        - name: CORE_PEER_TLS_KEY_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/server.key
        - name: CORE_PEER_TLS_ROOTCERT_FILE
          value: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/org1.example.com/peers/peer0.org1.example.com/tls/ca.crt
        - name: CORE_VM_ENDPOINT
          value: unix:///host/var/run/docker.sock
        - name: FABRIC_LOGGING_SPEC
          value: DEBUG
        - name: GOPATH
          value: /opt/gopath
        volumeMounts:
        - name: data
          mountPath: /opt/gopath/src/github.com/chaincode
          subPath: fabric-kubernetes/chaincode
        - name: docker
          mountPath: /host/var/run/
        - name: data
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
          subPath: fabric-kubernetes/crypto-config
        - name: data
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
          subPath: fabric-kubernetes/channel-artifacts
        - name: data
          mountPath: /opt/gopath/src/github.com/hyperledger/fabric/peer/scripts/
          subPath: fabric-kubernetes/scripts
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data-pvc
      - name: docker
        hostPath:
          path: /var/run
          type: Directory
