kind: PersistentVolume
apiVersion: v1
metadata:
  name: data-pv
  labels:
    type: local
spec:
  storageClassName: data
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/home/test/"

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data-pvc
spec:
  storageClassName: data
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
